name: gradient_widgets
description: Gradients on widgets
version: 0.2.0
author: bluemix <a.bluemix@gmail.com>
homepage: bluemix.github.io

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

